import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import seed from '../data/catalog.json' with {type:'json'};
import {productSchema,collectionSchema,settingsSchema,publicCatalog,httpsUrl,applicationSchema} from '../server/schema.mjs';
import {calculate,defaults} from '../lib/calculator.mjs';
import {passwordHash,verifyPassword,makeSession,decodeSession,assertOrigin} from '../server/auth.mjs';
import {writeRecord,readRecord,Conflict} from '../server/store.mjs';
import {dictionaries} from '../lib/i18n.js';
test('22 imported works and complete translations validate',()=>{assert.equal(seed.products.length,22);settingsSchema.parse(seed.settings);for(const p of seed.products){productSchema.parse(p);for(const l of ['en','es']){assert.ok(p.translations[l].name);assert.ok(p.translations[l].description)}}seed.collections.forEach(c=>collectionSchema.parse(c));for(const l of ['pt','en','es'])for(const v of Object.values(dictionaries[l]))assert.notEqual(v,undefined)});
test('free nativity cannot be converted to a member-only download',()=>{assert.equal(productSchema.safeParse({...seed.products[0],access:'members',exclusive:false}).success,false)});
test('reject malformed HTTPS, credentials and javascript links without throwing',()=>{for(const url of ['https://','https://user:pass@example.com','javascript:alert(1)','http://example.com'])assert.equal(httpsUrl.safeParse(url).success,false);assert.equal(httpsUrl.safeParse('https://makerworld.com/pt').success,true)});
test('free network registration needs no paid license and partnership consent is separate',()=>{const a=applicationSchema.parse({name:'Maker',city:'Maceió',state:'AL',country:'Brasil',whatsapp:'5582999999999',email:'maker@example.com',description:'Impressões',delivery:'Retirada',productIds:[seed.products[0].id],consent:true});assert.equal(a.partnershipConsent,false);assert.equal(a.licenseProof,undefined)});
test('directory shows free nativity without paid proof and keeps private contacts private',()=>{const data=structuredClone(seed);data.stores=[{id:'maker',name:'Maker',status:'approved',consent:true,partnershipConsent:true,email:'private@example.com',licenseProof:'',licenseUntil:'',productIds:[seed.products[0].id,seed.products[4].id]}];const out=publicCatalog(data);assert.deepEqual(out.stores[0].productIds,[seed.products[0].id]);assert.ok(!('email' in out.stores[0]));assert.ok(!('partnershipConsent' in out.stores[0]));assert.ok(!('filePath' in out.products[0]));data.stores[0].status='pending';assert.equal(publicCatalog(data).stores.length,0)});
test('hidden collections hide their works and directory entries',()=>{const data=structuredClone(seed);data.collections[0].published=false;assert.ok(publicCatalog(data).products.every(p=>p.collection!=='presepio'))});
test('pricing recovers both sales fees and desired profit margin',()=>{const r=calculate(defaults);assert.ok(Math.abs(r.profit/r.price-.35)<1e-12);assert.ok(Math.abs(r.price-r.cost-r.fees-r.profit)<1e-12);assert.equal(calculate({...defaults,quantity:3}).total,r.price*3);assert.throws(()=>calculate({...defaults,fees:65}));assert.throws(()=>calculate({...defaults,failure:100}));assert.throws(()=>calculate({...defaults,quantity:1.5}));assert.throws(()=>calculate({...defaults,grams:NaN}))});
test('password hashes and signed sessions reject invalid credentials',async()=>{process.env.ADMIN_SESSION_SECRET='test-only-secret-with-more-than-32-characters';const hash=await passwordHash('test-password-long');assert.equal(await verifyPassword('test-password-long',hash),true);assert.equal(await verifyPassword('wrong',hash),false);const token=await makeSession('v1');assert.equal((await decodeSession(token)).version,'v1');assert.equal(await decodeSession(token+'tampered'),null);assert.throws(()=>assertOrigin({headers:{origin:'https://evil.test',host:'site.test'}}));assert.throws(()=>assertOrigin({headers:{origin:'invalid',host:'site.test'}}))});
test('optimistic storage rejects stale overwrite',async()=>{const dir=await mkdtemp(join(tmpdir(),'tiolira-test-'));process.env.LOCAL_DATA_DIR=dir;try{const rev=await writeRecord('test.json',{name:'one'},null);await assert.rejects(writeRecord('test.json',{name:'bad'},null),Conflict);await writeRecord('test.json',{name:'two'},rev);assert.equal((await readRecord('test.json')).data.name,'two')}finally{delete process.env.LOCAL_DATA_DIR;await rm(dir,{recursive:true,force:true})}});

test('complete collection only matches makers offering all released pieces',async()=>{
 const {matchesStore}=await import('../lib/store-search.mjs');
 const products=[{id:'maria',collection:'presepio',access:'maker'},{id:'jose',collection:'presepio',access:'maker'},{id:'anjo',collection:'presepio',access:'soon'}];
 const store={city:'Maceió',state:'AL',country:'Brasil',productIds:['maria']};
 assert.equal(matchesStore(store,'maceio','maria',products),true);
 assert.equal(matchesStore(store,'maceio','collection:presepio',products),false);
 store.productIds.push('jose');assert.equal(matchesStore(store,'maceio','collection:presepio',products),true);
 assert.equal(matchesStore(store,'Recife','collection:presepio',products),false);
 assert.equal(matchesStore(store,'','collection:unknown',products),false);
});
