'use client';
import {useEffect,useState} from 'react';
const blank={supplier:'',code:'',description:'',url:'',expiresAt:'',active:true};
export default function AdminCoupons({preview}){
 const [coupons,setCoupons]=useState([]),[revision,setRevision]=useState(null),[draft,setDraft]=useState(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
 useEffect(()=>{if(preview)return;fetch('/api/admin/coupons').then(async r=>{const result=await r.json();if(!r.ok)throw Error(result.error);setCoupons(result.coupons);setRevision(result.revision);setLoaded(true)}).catch(e=>setMessage(e.message));},[preview]);
 async function save(e){e.preventDefault();setBusy(true);setMessage('');try{const r=await fetch('/api/admin/coupons',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({item:draft,revision})}),result=await r.json();if(!r.ok)throw Error(result.error);setCoupons(result.coupons);setRevision(result.revision);setDraft(null);setMessage('Cupom salvo. Apenas cupons ativos e dentro da validade aparecem para os parceiros.');}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 if(preview)return <p className="notice">Conecte o armazenamento e entre como administrador para cadastrar os cupons reais dos fornecedores.</p>;
 return <div className="club-library"><p>Cadastre os códigos e condições combinados com cada fornecedor. Desative um cupom para retirá-lo da área do parceiro.</p>{message&&<p className="status-message" role="status">{message}</p>}<button className="button primary" disabled={!loaded||busy} onClick={()=>setDraft({...blank,id:crypto.randomUUID()})}>Adicionar cupom</button>{draft&&<form className="admin-fields admin-panel" onSubmit={save}><label>Fornecedor<input required maxLength={150} value={draft.supplier} onChange={e=>setDraft({...draft,supplier:e.target.value})}/></label><label>Código do cupom<input required maxLength={100} value={draft.code} onChange={e=>setDraft({...draft,code:e.target.value})}/></label><label className="full">Desconto e condições<textarea required maxLength={1000} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>Link do fornecedor (HTTPS)<input type="url" required value={draft.url} onChange={e=>setDraft({...draft,url:e.target.value})}/></label><label>Válido até (horário de Brasília, opcional)<input type="date" value={draft.expiresAt?new Date(Date.parse(draft.expiresAt)-3*3600_000).toISOString().slice(0,10):''} onChange={e=>setDraft({...draft,expiresAt:e.target.value?new Date(`${e.target.value}T23:59:59-03:00`).toISOString():''})}/></label><label className="check"><input type="checkbox" checked={draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/>Ativo</label><div className="admin-actions full"><button className="button primary" disabled={busy}>{busy?'Salvando...':'Salvar cupom'}</button><button type="button" className="button outline" disabled={busy} onClick={()=>setDraft(null)}>Cancelar</button></div></form>}<div className="admin-list">{coupons.map(c=><article className="admin-row" key={c.id}><div><strong>{c.supplier} · {c.code}</strong><p>{c.description}</p><small>{!c.active?'Inativo':c.expiresAt&&Date.parse(c.expiresAt)<=Date.now()?'Expirado':'Ativo'}</small></div><button disabled={busy} onClick={()=>setDraft(c)}>Editar</button></article>)}{loaded&&!coupons.length&&<p className="notice">Nenhum cupom cadastrado.</p>}</div></div>;
}
