'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
export default function PartnerDashboard({lang,t,member,network,setNetwork,downloads,coupons,licenses,setLicenses,logout,busy}){
 const [selected,setSelected]=useState(null),[issuing,setIssuing]=useState(false),[message,setMessage]=useState(''),[copyMessage,setCopyMessage]=useState('');
 const dialog=useRef(null),locale={pt:'pt-BR',en:'en-US',es:'es-ES'}[lang];
 const localized=item=>({...item,...item.translations?.[lang]});
 const items=downloads.map(localized),eligible=items.filter(item=>item.canLicense),license=licenses.find(l=>l.productId===selected?.id);
 useEffect(()=>{if(selected){setMessage('');setCopyMessage('');dialog.current.showModal();}},[selected]);
 async function joinNetwork(event){event.preventDefault();setIssuing(true);setMessage('');try{const response=await fetch('/api/club/network',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({consent:true})});const data=await response.json();if(!response.ok)throw Error(data.error||t.clubError);setNetwork(data.network);if(!data.network)setMessage(t.registrationClosed);}catch(error){setMessage(error.message)}finally{setIssuing(false)}}
 async function copy(code){try{await navigator.clipboard.writeText(code);setCopyMessage(t.clubCopied)}catch{setCopyMessage(t.clubCopyError)}}
 async function generate(){setIssuing(true);setMessage('');try{const r=await fetch('/api/club/licenses',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({productId:selected.id})}),result=await r.json();if(!r.ok)throw Error(result.error||t.clubError);setLicenses(current=>[...current.filter(l=>l.productId!==result.license.productId),result.license]);}catch(e){setMessage(e.message)}finally{setIssuing(false)}}
 const date=value=>new Date(value).toLocaleDateString(locale,{timeZone:'America/Maceio'});
 function receipt(item){return <div className="partner-license-receipt"><p className="eyebrow">{t.clubLicenseCode}</p><code>{item.code}</code><p>{t.clubLicensePartner}: <strong>{item.partnerName}</strong></p><p>{t.clubLicenseIssued} {date(item.issuedAt)}</p><p>{t.clubLicenseTerms}</p>{item.productTerms&&<p>{item.productTerms}</p>}<button className="button outline" onClick={()=>copy(item.code)}>{t.clubCopy}</button></div>}
 return <section className="club-dashboard"><div className="club-dashboard-top"><div><p className="eyebrow">{t.clubWelcome}</p><h2>{member.name}</h2><p>{member.email}</p></div><button className="button outline" onClick={logout} disabled={busy}>{t.clubLogout}</button></div><nav className="partner-nav" aria-label={t.clubArea}><a href="#colecoes-parceiro">{t.collections}</a><a href="#cupons">{t.clubCoupons}</a><a href="#licencas">{t.clubLicenses}</a></nav>
 <div className="network-benefit"><div><h3>{t.clubReferrals}</h3><p>{t.clubReferralsIntro}</p>{network?<p role="status">{t[`clubNetwork_${network.status}`]}</p>:<form onSubmit={joinNetwork}><label className="check"><input type="checkbox" required/> <span>{t.consent}</span></label><button className="button primary" disabled={issuing}>{t.clubActivateNetwork}</button></form>}</div><Link className="button outline" href={`/${lang}#lojas`}>{t.clubJoinNetwork}</Link></div>
 {message&&!selected&&<p role="alert" className="status-message">{message}</p>}
 <section className="club-library" id="colecoes-parceiro"><div className="section-heading"><h2>{t.clubLibraryTitle}</h2></div>{items.length?<div className="club-download-grid">{items.map(item=><article className="club-download-card" key={item.id}><button className="partner-piece-image" aria-label={`${t.details}: ${item.name}`} onClick={()=>setSelected(item)}><img src={item.image} alt=""/></button><div><h3>{item.name}</h3><button className="button outline" onClick={()=>setSelected(item)}>{item.canLicense?t.clubLicenseView:t.details}</button></div></article>)}</div>:<p className="notice">{t.clubNoFiles}</p>}</section>
 <section className="club-library" id="cupons"><h2>{t.clubCoupons}</h2><p>{t.clubCouponsIntro}</p>{coupons.length?<div className="partner-coupon-grid">{coupons.map(c=><article className="partner-coupon" key={c.id}><p className="eyebrow">{c.supplier}</p><h3>{c.description}</h3><code>{c.code}</code>{c.expiresAt&&<p>{t.clubCouponExpires} {date(c.expiresAt)}</p>}<div className="partner-actions"><button className="button outline" onClick={()=>copy(c.code)}>{t.clubCopy}</button><a className="button primary" href={c.url} target="_blank" rel="noreferrer">{t.clubCouponStore} ↗</a></div></article>)}</div>:<p className="notice">{t.clubNoCoupons}</p>}</section>
 <section className="club-library" id="licencas"><h2>{t.clubLicenses}</h2><p>{t.clubLicensesIntro}</p>{eligible.length?<div className="partner-license-list">{eligible.map(item=><button className="partner-license-choice" key={item.id} onClick={()=>setSelected(item)}><img src={item.image} alt=""/><span><strong>{item.name}</strong><small>{t.clubLicenseView} →</small></span></button>)}</div>:<p className="notice">{t.clubNoLicenses}</p>}{licenses.length>0&&<><h3>{t.clubMyLicenses}</h3>{licenses.map(item=><details className="partner-saved-license" key={item.code}><summary>{item.productName}</summary>{receipt(item)}</details>)}</>}</section>
 {copyMessage&&<p role="status" className="status-message">{copyMessage}</p>}
 <dialog ref={dialog} className="admin-editor partner-piece-dialog" aria-labelledby="partner-piece-title" onClose={()=>setSelected(null)}><button className="close-dialog" aria-label={t.close} onClick={()=>dialog.current.close()}>×</button>{selected&&<><img className="partner-dialog-image" src={selected.image} alt=""/><h2 id="partner-piece-title">{selected.name}</h2>{selected.downloadUrl&&<a className="button primary" href={selected.downloadUrl} target={selected.downloadUrl.startsWith('https:')?'_blank':undefined} rel="noreferrer">{selected.access==='maker'?t.makerDownload:t.download} ↓</a>}{selected.canLicense&&<div className="club-library"><h3>{t.clubLicenses}</h3>{license?receipt(license):<><p>{t.clubLicenseTerms}</p><button className="button outline" disabled={issuing} onClick={generate}>{issuing?t.clubWait:t.clubLicenseGenerate}</button></>}</div>}{message&&<p role="alert" className="status-message">{message}</p>}{copyMessage&&<p role="status">{copyMessage}</p>}</>}</dialog></section>;
}
