'use client';
import {useRef,useState} from 'react';
import {dictionaries,localized} from '../lib/i18n';
const norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
export default function StoreNetwork({lang,catalog}){
 const t=dictionaries[lang],dialog=useRef(null),[city,setCity]=useState(''),[piece,setPiece]=useState('all'),[searched,setSearched]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const found=catalog.stores.filter(s=>(!city||norm(`${s.city} ${s.state} ${s.country}`).includes(norm(city)))&&(piece==='all'||s.productIds.includes(piece)));
 async function submit(e){e.preventDefault();if(!catalog.registrationReady)return;setBusy(true);setMessage('');const f=new FormData(e.currentTarget);const data=Object.fromEntries(f);data.productIds=f.getAll('productIds');data.consent=f.has('consent');data.partnershipConsent=f.has('partnershipConsent');data.whatsapp=data.whatsapp.replace(/\D/g,'');try{const r=await fetch('/api/stores/apply',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw Error();setMessage(t.sent);e.target.reset();}catch{setMessage(t.error)}finally{setBusy(false)}}
 return <section className="store-section wrap section" id="lojas"><div className="store-heading"><div><p className="eyebrow">{t.shopEyebrow}</p><h2>{t.shopTitle}</h2></div><p>{t.shopIntro}</p></div><div className="store-shell"><div className="store-search-panel"><span className="store-icon">⌖</span><h3>{t.stores}</h3><form onSubmit={e=>{e.preventDefault();setSearched(true)}}><label htmlFor="store-city">{t.city}</label><input id="store-city" placeholder="Maceió, Recife, São Paulo…" value={city} onChange={e=>setCity(e.target.value)}/><label htmlFor="store-piece">{t.piece}</label><select id="store-piece" value={piece} onChange={e=>setPiece(e.target.value)}><option value="all">{t.all}</option>{catalog.products.map(p=><option key={p.id} value={p.id}>{localized(p,lang).name}</option>)}</select><button className="button primary">{t.find} →</button></form><button className="store-register" onClick={()=>dialog.current.showModal()}>{t.join} ↗</button></div><div className="store-results-panel"><span className="network-label">{t.join} · {t.freeNativity}</span><div className="store-results" aria-live="polite">{(searched||!catalog.stores.length)&&!found.length?<div className="store-empty"><span>⌖</span><h3>{catalog.stores.length?t.noMatch:t.noStores}</h3><p>{t.joinIntro}</p></div>:found.map(s=><article className="store-card" key={s.id}><h3>{s.name}</h3><p>{s.city}, {s.state} · {s.country}</p><p>{s.description}</p><p className="store-delivery">{s.delivery}</p><a className="store-contact" href={`https://wa.me/${s.whatsapp}?text=${encodeURIComponent({pt:'Olá! Encontrei seu contato na rede do Tio Lira. Gostaria de um orçamento.',en:'Hello! I found you on the Tio Lira network. I would like a quote.',es:'¡Hola! Te encontré en la red de Tio Lira. Quisiera un presupuesto.'}[lang])}`} target="_blank" rel="noreferrer">{t.quote} ↗</a></article>)}</div><p className="store-disclaimer">{t.disclaimer}</p></div></div>
 <dialog className="seller-form" ref={dialog} aria-labelledby="join-title"><button className="close-dialog" aria-label={t.close} onClick={()=>dialog.current.close()}>×</button><p className="eyebrow">{t.join}</p><h2 id="join-title">{t.joinTitle}</h2><p>{t.joinIntro}</p>{!catalog.registrationReady&&<p className="notice">{t.previewForm}</p>}<form onSubmit={submit} className="form-grid"><label>{t.name}<input name="name" required maxLength={200}/></label><label>{t.email}<input name="email" type="email" required maxLength={254}/></label><label>{t.city}<input name="city" required maxLength={120}/></label><label>{t.state}<input name="state" required maxLength={120}/></label><label>{t.country}<input name="country" required defaultValue={lang==='pt'?'Brasil':''} maxLength={100}/></label><label>{t.whatsapp}<input name="whatsapp" type="tel" required placeholder="55 82 99999-9999"/></label><label className="full">{t.website}<input name="website" type="url" placeholder="https://"/></label><label className="full">{t.delivery}<input name="delivery" required maxLength={500}/></label><label className="full">{t.description}<textarea name="description" required maxLength={2000}/></label><fieldset className="full model-options"><legend>{t.models}</legend>{catalog.products.filter(p=>p.access!=='soon').map(p=><label key={p.id}><input type="checkbox" name="productIds" value={p.id}/>{localized(p,lang).name}</label>)}</fieldset><label className="check full"><input type="checkbox" name="consent" required/>{t.consent}</label><label className="check full"><input type="checkbox" name="partnershipConsent"/>{t.partnership}</label><div className="honey" aria-hidden="true"><label>Website confirmation<input name="honeypot" tabIndex={-1} autoComplete="off"/></label></div><button className="button primary full" disabled={busy||!catalog.registrationReady}>{busy?t.loading:t.submit}</button>{message&&<p className="notice full" role="status">{message}</p>}</form></dialog></section>
}
