'use client';
import {useState} from 'react';
import Link from 'next/link';
import Header from './Header';
import Footer from './Footer';
import StoreNetwork from './StoreNetwork';
import {dictionaries,localized} from '../lib/i18n';
const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
export default function Studio({lang,catalog}){
 const t=dictionaries[lang],s=localized(catalog.settings,lang),collections=catalog.collections.map(c=>localized(c,lang));
 const [filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[onlyAvailable,setOnlyAvailable]=useState(false),[limit,setLimit]=useState(6);
 const products=catalog.products.map(p=>localized(p,lang)).filter(p=>(filter==='all'||p.collection===filter)&&(!onlyAvailable||p.access!=='soon')&&normalize(p.name+' '+p.description).includes(normalize(query)));
 function choose(id){setFilter(id);setQuery('');setLimit(6);}
 return <><a className="skip" href="#obras">{t.works}</a><div className="announcement"><span>{s.announcement}</span><a href="#clube">{t.nextCollections} ↗</a></div><Header lang={lang}/><main>
 <section className="hero wrap" id="inicio"><div className="hero-copy"><p className="eyebrow"><span className="line"/>{t.gift}</p><h1>{s.heroTitle.split(' ').slice(0,-2).join(' ')}<br/><em>{s.heroTitle.split(' ').slice(-2).join(' ')}</em></h1><p className="hero-description">{s.heroDescription}</p><div className="hero-actions"><a className="button primary" href="#obras" onClick={()=>choose('presepio')}>{t.downloadNativity} ↗</a><a className="text-link" href="#lojas">{t.sell} →</a></div><div className="maker-note"><span className="seal">TL</span><p>{t.madeBy}<br/><strong>{t.fromBrazil}</strong></p></div></div>
 <div className="hero-art"><span className="art-coordinate">01 / {collections[0]?.name}</span><div className="art-halo"/><figure className="art-back"><img src="/assets/382acfa0a193fa49.jpg" alt={lang==='en'?'Joseph':'José'} fetchPriority="high"/><figcaption>01 / {lang==='en'?'JOSEPH':'JOSÉ'}</figcaption></figure><figure className="art-front"><img src="/assets/603ea2ab9c97d1fc.jpg" alt={lang==='en'?'Mary':'Maria'} fetchPriority="high"/><figcaption><span>{t.christmas}<br/><b>{t.memories}</b></span><a href="#obras" onClick={()=>choose('presepio')} aria-label={t.downloadNativity}>↗</a></figcaption></figure><div className="floating-label"><span>✧</span><span>{t.freeNativity}<br/>{t.fromBrazil}</span></div><p className="art-caption">{t.render}</p></div></section>
 <div className="ribbon"><div className="wrap"><span>{t.original}</span><i>✳</i><span>{t.freeNativity}</span><i>✳</i><span>{t.nextCollections}</span></div></div>
 <section className="collections wrap section" id="colecoes"><div className="section-heading"><div><p className="eyebrow">{t.universe}</p><h2>{t.collectionTitle}</h2></div></div><div className="collection-grid">{collections.map((c,i)=><a key={c.id} className={`collection-tile ${['nativity','faith','roots'][i%3]}`} href="#obras" onClick={()=>choose(c.id)}><img src={c.image} alt={c.name} loading="lazy"/><span className="tile-top">0{i+1} — {c.free?t.free:t.members}<span>↗</span></span><span className="tile-bottom"><small>{c.description}</small><strong>{c.name}</strong><span>{t.explore} →</span></span></a>)}</div></section>
 <section className="catalog-section" id="obras"><div className="wrap section"><div className="section-heading"><div><p className="eyebrow">{t.catalogEyebrow}</p><h2>{t.catalogTitle}</h2></div><label className="search"><span>⌕</span><input type="search" placeholder={t.search} aria-label={t.search} value={query} onChange={e=>{setQuery(e.target.value);setLimit(6)}}/></label></div><div className="catalog-toolbar"><div className="filters"><button aria-pressed={filter==='all'} onClick={()=>choose('all')}>{t.all}</button>{collections.map(c=><button key={c.id} aria-pressed={filter===c.id} onClick={()=>choose(c.id)}>{c.name}</button>)}</div><label className="availability"><input type="checkbox" checked={onlyAvailable} onChange={e=>setOnlyAvailable(e.target.checked)}/>{t.available}</label></div><div className="catalog-meta"><span role="status">{products.length} {t.results}</span><span>{t.digital}</span></div><div className="product-grid">{products.slice(0,limit).map(p=><article className="product-card" key={p.id}><Link className="product-image" href={`/${lang}/produto/${p.slug}`}><img src={p.image} alt={p.name} loading="lazy"/><span className={`badge ${p.access==='soon'?'coming':''}`}>{t[p.access==='site'?'free':p.access]}</span><span className="image-arrow">↗</span></Link><div className="product-info"><p className="category">{collections.find(c=>c.id===p.collection)?.name}</p><h3>{p.name}</h3><div className="product-bottom"><Link href={`/${lang}/produto/${p.slug}`}>{t.details} →</Link>{p.size&&<span>{p.size}</span>}</div></div></article>)}</div>{products.length===0&&<p className="empty">{t.none}</p>}{products.length>limit&&<div className="more-wrap"><button className="button outline" onClick={()=>setLimit(limit+6)}>{t.more} ↓</button></div>}</div></section>
 <section className="gift-note wrap"><span>♡</span><div><h3>{t.freeNativity}</h3><p>{t.physicalLicense}</p></div></section>
 <StoreNetwork lang={lang} catalog={catalog}/>
 <section className="club wrap section" id="clube"><div className="club-panel"><div className="club-intro"><p className="eyebrow">{t.club} · {t.soon}</p><h2>{t.exclusiveTitle}</h2><p>{s.clubDescription}</p><a className="button cream" href={s.instagram} target="_blank" rel="noreferrer">{t.updates} ↗</a><small>{t.exclusiveNote}</small></div><div className="license-card"><span className="license-mark">✳</span><p className="eyebrow">{t.nextCollections}</p><h3>{t.club}</h3><ul>{t.clubFeatures.map(f=><li key={f}><span>✓</span>{f}</li>)}</ul><div className="license-foot">{t.exclusiveNote}</div>{catalog.plans.filter(p=>p.status==='active').map(p=><a key={p.id} className="button primary" href={p.url} target="_blank" rel="noreferrer">{localized(p,lang).name} · {p.priceLabel} ↗</a>)}</div></div></section>
 <section className="about wrap" id="sobre"><div className="about-art"><img src="/assets/efc464ed6ed95396.jpg" alt={t.original} loading="lazy"/><span>{t.fromBrazil}</span></div><div className="about-copy"><p className="eyebrow">{t.aboutEyebrow}</p><h2>{t.aboutTitle}</h2><p>{s.about}</p><a className="text-link" href={s.instagram} target="_blank" rel="noreferrer">{t.instagram} ↗</a><span className="signature">Diego Lira</span></div></section>
 <section className="faq wrap section"><div><p className="eyebrow">TIO LIRA / FAQ</p><h2>{t.faqTitle}</h2><Link className="calculator-link" href={`/${lang}/calculadora`}>{t.sell}<br/><strong>{t.calculator} ↗</strong></Link></div><div className="faq-list">{t.faq.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
 </main><Footer lang={lang}/></>;
}
