const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const copy={
 pt:{subject:'Defina sua senha — Clube Tio Lira',preheader:'Seu acesso à área do parceiro, em um clique.',studio:'ESTÚDIO DE CRIAÇÃO 3D',eyebrow:'CLUBE TIO LIRA · ÁREA DO PARCEIRO',title:'Vamos cuidar do seu acesso.',hello:'Olá',intro:'Recebemos um pedido para definir ou alterar a senha da sua conta. Clique no botão abaixo para continuar.',button:'Definir minha senha',expiry:'Este link é válido por 30 minutos e pode ser usado uma única vez.',fallback:'Se o botão não abrir, copie e cole este endereço no navegador:',ignore:'Se você não fez esse pedido, pode ignorar este e-mail. Sua senha permanece a mesma.',footer:'Feito de fé, afeto e criatividade brasileira.',rights:'Criações autorais.',visit:'Visite nosso site'},
 en:{subject:'Set your password — Tio Lira Club',preheader:'Your partner area is one click away.',studio:'3D CREATIVE STUDIO',eyebrow:'TIO LIRA CLUB · PARTNER AREA',title:'Let’s get you back in.',hello:'Hello',intro:'We received a request to set or change your account password. Click the button below to continue.',button:'Set my password',expiry:'This link is valid for 30 minutes and can only be used once.',fallback:'If the button does not work, copy and paste this address into your browser:',ignore:'If you did not request this, you can ignore this email. Your password stays the same.',footer:'Made with faith, care and Brazilian creativity.',rights:'Original creations.',visit:'Visit our website'},
 es:{subject:'Define tu contraseña — Club Tio Lira',preheader:'Tu área de socios, a un clic.',studio:'ESTUDIO DE CREACIÓN 3D',eyebrow:'CLUB TIO LIRA · ÁREA DE SOCIOS',title:'Cuidemos de tu acceso.',hello:'Hola',intro:'Recibimos una solicitud para definir o cambiar la contraseña de tu cuenta. Haz clic en el botón para continuar.',button:'Definir mi contraseña',expiry:'Este enlace es válido por 30 minutos y solo se puede usar una vez.',fallback:'Si el botón no funciona, copia y pega esta dirección en el navegador:',ignore:'Si no hiciste esta solicitud, puedes ignorar este correo. Tu contraseña permanece igual.',footer:'Hecho con fe, cariño y creatividad brasileña.',rights:'Creaciones originales.',visit:'Visita nuestro sitio'}
};
export function passwordResetEmail({name,lang='pt',origin,link}){
 lang=Object.hasOwn(copy,lang)?lang:'pt';const t=copy[lang];
 const site=new URL(origin),reset=new URL(link);
 if(site.protocol!=='https:'||site.username||site.password||reset.origin!==site.origin||reset.username||reset.password||reset.pathname!==`/${lang}/clube`||!/^#reset=[a-f0-9]{64}$/.test(reset.hash))throw Error('Invalid recovery URL');
 const root=escapeHtml(site.origin),url=escapeHtml(reset.href),greeting=`${t.hello}${name?`, ${name}`:''}!`;
 const html=`<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light"><title>${t.subject}</title></head>
<body style="margin:0;padding:0;background-color:#f8f6f0;color:#292b25;font-family:Arial,Helvetica,sans-serif;">
<div style="display:none;font-size:1px;color:#f8f6f0;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden;mso-hide:all;">${t.preheader}</div>
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="background-color:#f8f6f0;"><tr><td align="center" style="padding:28px 16px;">
<!--[if mso]><table role="presentation" width="600" align="center"><tr><td><![endif]-->
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="max-width:600px;margin:auto;">
<tr><td style="padding:8px 8px 28px;border-bottom:1px solid #deded3;"><a href="${root}/${lang}" style="text-decoration:none;color:#292b25;"><table role="presentation" cellspacing="0" cellpadding="0" border="0"><tr><td width="64"><img src="${root}/assets/tl-monogram-3d-icon.png" alt="TL" width="52" height="52" style="display:block;border:0;width:52px;height:52px;"></td><td><span style="font-size:30px;font-weight:700;letter-spacing:-1px;line-height:34px;">tio lira</span><br><span style="font-size:9px;letter-spacing:2px;font-weight:700;">${t.studio}</span></td></tr></table></a></td></tr>
<tr><td style="padding:32px 0 0;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="background-color:#fffdf8;border:1px solid #deded3;border-radius:14px;">
<tr><td style="padding:26px 28px;background-color:#404934;border-radius:13px 13px 0 0;color:#ffffff;"><p style="margin:0 0 12px;font-size:10px;letter-spacing:2px;font-weight:700;color:#e6ebdf;">${t.eyebrow}</p><h1 style="margin:0;font-size:30px;line-height:1.2;letter-spacing:-1px;font-weight:500;color:#ffffff;">${t.title}</h1></td></tr>
<tr><td style="padding:30px 28px;"><p style="margin:0 0 16px;font-size:17px;font-weight:700;line-height:1.5;">${escapeHtml(greeting)}</p><p style="margin:0 0 26px;font-size:15px;line-height:1.7;color:#696b61;">${t.intro}</p>
<table role="presentation" cellspacing="0" cellpadding="0" border="0"><tr><td align="center" bgcolor="#c7512f" style="border-radius:7px;"><a href="${url}" style="display:inline-block;padding:16px 24px;border:1px solid #c7512f;border-radius:7px;font-size:15px;font-weight:700;text-decoration:none;color:#ffffff;background-color:#c7512f;mso-padding-alt:16px 24px;">${t.button} &rarr;</a></td></tr></table>
<p style="margin:20px 0 26px;padding:14px 16px;background-color:#edf0e6;border-radius:7px;font-size:12px;line-height:1.6;color:#404934;">${t.expiry}</p>
<p style="margin:0 0 8px;font-size:12px;line-height:1.6;color:#696b61;">${t.fallback}</p><p style="margin:0 0 24px;font-size:11px;line-height:1.7;word-break:break-all;overflow-wrap:anywhere;"><a href="${url}" style="color:#404934;text-decoration:underline;word-break:break-all;">${url}</a></p>
<p style="margin:0;padding-top:20px;border-top:1px solid #deded3;font-size:12px;line-height:1.6;color:#696b61;">${t.ignore}</p></td></tr></table></td></tr>
<tr><td align="center" style="padding:28px 16px 8px;"><p style="margin:0 0 12px;font-size:13px;color:#404934;">${t.footer}</p><p style="margin:0 0 14px;font-size:12px;"><a href="${root}/${lang}" style="color:#404934;text-decoration:underline;">tiolira.com.br</a><span style="color:#b8bcae;"> &nbsp;·&nbsp; </span><a href="https://www.instagram.com/tiolira/" style="color:#404934;text-decoration:underline;">Instagram</a></p><p style="margin:0;font-size:10px;line-height:1.6;color:#696b61;">© ${new Date().getUTCFullYear()} Diego Lira. ${t.rights}</p></td></tr>
</table><!--[if mso]></td></tr></table><![endif]-->
</td></tr></table></body></html>`;
 return {subject:t.subject,html,text:`Tio Lira — ${t.studio}\n\n${greeting}\n\n${t.intro}\n\n${t.button}:\n${reset.href}\n\n${t.expiry}\n\n${t.ignore}\n\n${t.footer}\n${site.origin}`};
}
