export const languages = ['pt','en','es'];
export const localeNames = {pt:'Português',en:'English',es:'Español'};
export function localized(item,lang){return {...item,...item.translations?.[lang]};}
const rows={
 studio:['ESTÚDIO DE CRIAÇÃO 3D','3D DESIGN STUDIO','ESTUDIO DE CREACIÓN 3D'],
 collections:['Coleções','Collections','Colecciones'],works:['Obras','Models','Obras'],stores:['Rede de lojas','Maker network','Red de tiendas'],club:['Clube Tio Lira','Tio Lira Club','Club Tio Lira'],about:['O criador','The creator','El creador'],
 gift:['UM PRESENTE FEITO DE FÉ E AFETO','A GIFT OF FAITH AND LOVE','UN REGALO DE FE Y CARIÑO'],
 downloadNativity:['Explorar o presépio gratuito','Explore the free nativity','Explorar el belén gratuito'],sell:['Quero imprimir para vender','I want to print and sell','Quiero imprimir para vender'],
 madeBy:['Modelado por Diego Lira.','Designed by Diego Lira.','Diseñado por Diego Lira.'],fromBrazil:['Do Brasil, para a sua criatividade.','From Brazil, for your creativity.','Desde Brasil, para tu creatividad.'],
 christmas:['Um Natal para criar.','A Christmas to create.','Una Navidad para crear.'],memories:['E guardar na memória.','And remember forever.','Y guardar en la memoria.'],
 original:['MODELOS AUTORAIS','ORIGINAL MODELS','MODELOS ORIGINALES'],freeNativity:['PRESÉPIO GRATUITO','FREE NATIVITY','BELÉN GRATUITO'],nextCollections:['COLEÇÕES EXCLUSIVAS A CAMINHO','EXCLUSIVE COLLECTIONS COMING','NUEVAS COLECCIONES EXCLUSIVAS'],
 universe:['UM UNIVERSO DE POSSIBILIDADES','A WORLD OF POSSIBILITIES','UN MUNDO DE POSIBILIDADES'],collectionTitle:['Cada coleção, uma história.','Every collection tells a story.','Cada colección, una historia.'],explore:['Explorar a coleção','Explore the collection','Explorar la colección'],
 catalogEyebrow:['DA IDEIA À IMPRESSÃO','FROM IDEA TO PRINT','DE LA IDEA A LA IMPRESIÓN'],catalogTitle:['Sua próxima criação começa aqui.','Your next creation starts here.','Tu próxima creación empieza aquí.'],search:['Buscar uma peça...','Search for a model...','Buscar una pieza...'],all:['Todas as obras','All models','Todas las obras'],available:['Só disponíveis','Available now','Solo disponibles'],results:['obras encontradas','models found','obras encontradas'],digital:['Arquivos digitais para impressão 3D','Digital files for 3D printing','Archivos digitales para impresión 3D'],more:['Explorar mais obras','Explore more models','Explorar más obras'],none:['Nenhuma peça encontrada. Tente outro nome.','No models found. Try another name.','No hay resultados. Prueba otro nombre.'],
 free:['Gratuito','Free','Gratis'],maker:['Grátis no MakerWorld','Free on MakerWorld','Gratis en MakerWorld'],soon:['Em breve','Coming soon','Próximamente'],members:['Coleção exclusiva','Exclusive collection','Colección exclusiva'],details:['Conhecer a obra','View model','Ver obra'],download:['Baixar gratuitamente','Download for free','Descargar gratis'],makerDownload:['Baixar no MakerWorld','Download on MakerWorld','Descargar en MakerWorld'],originalPage:['Baixar no site original','Download on original site','Descargar en el sitio original'],notReleased:['Lançamento em preparação.','Release in preparation.','Lanzamiento en preparación.'],back:['Voltar ao catálogo','Back to catalog','Volver al catálogo'],size:['Dimensões de referência','Reference dimensions','Dimensiones de referencia'],instructions:['Sobre esta criação','About this creation','Sobre esta creación'],license:['Licença de uso','Usage license','Licencia de uso'],render:['Imagens ilustrativas de apresentação dos modelos.','Illustrative presentation images of the models.','Imágenes ilustrativas de presentación de los modelos.'],
 physicalLicense:['O presépio é gratuito, inclusive para imprimir e vender as peças físicas. Não é preciso assinar o clube. Os arquivos digitais não podem ser revendidos ou redistribuídos. Os downloads exclusivos permanecem no MakerWorld.','The nativity is free, including permission to print and sell physical pieces. No club subscription is needed. Digital files must not be resold or redistributed. Exclusive downloads remain on MakerWorld.','El belén es gratuito, incluido el permiso para imprimir y vender las piezas físicas. No necesitas suscribirte al club. No se pueden revender ni redistribuir los archivos digitales. Las descargas exclusivas permanecen en MakerWorld.'],
 otherLicense:['Consulte a licença específica na página do modelo antes de vender impressões. Arquivos digitais não podem ser revendidos ou compartilhados.','Check the model’s specific license before selling prints. Digital files must not be resold or shared.','Consulta la licencia específica del modelo antes de vender impresiones. No se pueden revender ni compartir los archivos digitales.'],
 shopEyebrow:['A CRIAÇÃO CONECTA PESSOAS','CREATIVITY CONNECTS PEOPLE','LA CREATIVIDAD CONECTA PERSONAS'],shopTitle:['Encontre quem imprime perto de você.','Find a maker near you.','Encuentra quién imprime cerca de ti.'],shopIntro:['Não tem impressora? Encontre uma pessoa ou loja, peça um orçamento e combine sua peça diretamente.','No printer? Find a maker or shop, request a quote and arrange your piece directly.','¿No tienes impresora? Encuentra una persona o tienda, pide presupuesto y acuerda tu pieza directamente.'],city:['Cidade','City','Ciudad'],state:['Estado / região','State / region','Estado / región'],country:['País','Country','País'],piece:['Qual peça você procura?','Which model are you looking for?','¿Qué pieza buscas?'],find:['Encontrar quem imprime','Find makers','Buscar quién imprime'],join:['Cadastrar gratuitamente','Join for free','Registrarme gratis'],noStores:['Nossa rede está começando. Seja um dos primeiros a participar.','Our network is just getting started. Be one of the first to join.','Nuestra red está empezando. Sé de los primeros en participar.'],noMatch:['Ainda não há participantes para esta busca.','No makers match this search yet.','Aún no hay participantes para esta búsqueda.'],quote:['Pedir orçamento','Request a quote','Pedir presupuesto'],disclaimer:['Preço, prazo, entrega e pagamento são combinados diretamente com o vendedor.','Price, timing, delivery and payment are arranged directly with the seller.','Precio, plazo, entrega y pago se acuerdan directamente con el vendedor.'],
 joinTitle:['Sua impressora. Novas conexões.','Your printer. New connections.','Tu impresora. Nuevas conexiones.'],joinIntro:['Cadastro gratuito para pessoas e lojas. Você pode vender as peças físicas do presépio sem assinatura. Os cadastros passam por uma revisão antes de aparecer na rede.','Free registration for individuals and shops. You can sell physical nativity prints without subscribing. Applications are reviewed before appearing in the network.','Registro gratuito para personas y tiendas. Puedes vender las piezas físicas del belén sin suscripción. Revisamos los registros antes de publicarlos en la red.'],
 name:['Seu nome ou nome da loja','Your name or shop name','Tu nombre o el de tu tienda'],email:['E-mail privado','Private email','Correo privado'],whatsapp:['WhatsApp comercial com código do país','Business WhatsApp with country code','WhatsApp comercial con código de país'],website:['Site ou Instagram (opcional)','Website or Instagram (optional)','Sitio web o Instagram (opcional)'],delivery:['Região atendida / envio','Service area / shipping','Zona de atención / envíos'],description:['Conte um pouco sobre seu trabalho','Tell us about your work','Cuéntanos sobre tu trabajo'],models:['Quais peças você imprime?','Which models do you print?','¿Qué piezas imprimes?'],consent:['Autorizo a publicação do nome, cidade, contato comercial e informações do meu trabalho na rede. Meu e-mail fica privado.','I consent to publishing my name, city, business contact and work information in the network. My email stays private.','Autorizo la publicación de mi nombre, ciudad, contacto comercial e información de mi trabajo. Mi correo permanece privado.'],partnership:['Quero receber contatos do Tio Lira sobre futuras parcerias (opcional).','I would like Tio Lira to contact me about future partnerships (optional).','Quiero que Tio Lira me contacte sobre futuras colaboraciones (opcional).'],submit:['Enviar cadastro gratuito','Submit free application','Enviar registro gratuito'],sent:['Cadastro recebido! Vamos revisar suas informações antes de publicar.','Application received! We will review your information before publishing.','¡Registro recibido! Revisaremos tus datos antes de publicarlos.'],previewForm:['Prévia: o cadastro será ativado quando o banco de dados for conectado. Nenhum dado deste formulário é enviado ou armazenado agora.','Preview: registration will open when the database is connected. No information from this form is sent or stored now.','Vista previa: el registro se activará al conectar la base de datos. No se envían ni guardan datos de este formulario ahora.'],
 exclusiveTitle:['Muita coisa boa ainda vai ganhar forma.','Wonderful things are taking shape.','Muchas cosas bonitas están tomando forma.'],exclusiveNote:['O presépio continua gratuito. As futuras coleções exclusivas terão suas próprias condições, apresentadas antes da abertura das assinaturas.','The nativity stays free. Future exclusive collections will have their own terms, announced before subscriptions open.','El belén sigue siendo gratuito. Las futuras colecciones exclusivas tendrán sus propias condiciones, anunciadas antes de abrir las suscripciones.'],clubFeatures:[['Coleções autorais selecionadas','Licença para vender peças físicas','Arquivos digitais sem direito de revenda','Novidades para acompanhar de perto'],['Selected original collections','License to sell physical prints','No resale rights for digital files','New releases to look forward to'],['Colecciones originales seleccionadas','Licencia para vender piezas físicas','Sin reventa de archivos digitales','Novedades para seguir de cerca']],updates:['Acompanhar novidades','Follow the updates','Seguir las novedades'],
 aboutEyebrow:['PRAZER, EU SOU O TIO LIRA.','HELLO, I’M TIO LIRA.','HOLA, SOY TIO LIRA.'],aboutTitle:['A tecnologia é 3D. A inspiração é a vida.','The technology is 3D. The inspiration is life.','La tecnología es 3D. La inspiración es la vida.'],instagram:['Bastidores no Instagram','Behind the scenes on Instagram','Entre bastidores en Instagram'],
 faqTitle:['Boas perguntas. Respostas simples.','Good questions. Simple answers.','Buenas preguntas. Respuestas sencillas.'],faq:[[
['O presépio é mesmo gratuito?','Sim! É um presente de carinho e atenção a todos. Você pode baixar as peças já lançadas e acompanhar as próximas. Não é necessário assinar o clube.'],['Posso imprimir o presépio para vender?','Sim. Tio Lira autoriza a venda das peças físicas do presépio, sem assinatura. A revenda ou redistribuição dos arquivos digitais não é permitida.'],['Preciso ter uma loja para me cadastrar?','Não. Pessoas que imprimem em casa e lojas podem se cadastrar gratuitamente. Você informa sua cidade e seu contato comercial para receber pedidos.'],['Por que alguns arquivos estão no MakerWorld?','Alguns modelos são exclusivos dessa plataforma. O site leva você à página oficial, onde estão o arquivo e as instruções.'],['As assinaturas já estão abertas?','Ainda não. Várias coleções exclusivas estão chegando. Catálogo, preços e regras serão anunciados antes da abertura.']],
[['Is the nativity really free?','Yes! It is a gift of care and affection for everyone. Download the released models and follow the next ones. No subscription is required.'],['Can I print the nativity to sell?','Yes. Tio Lira allows the sale of physical nativity prints without a subscription. Reselling or redistributing digital files is not allowed.'],['Do I need a shop to join?','No. Home makers and shops can register for free. Provide your city and business contact to receive inquiries.'],['Why are some files on MakerWorld?','Some models are exclusive to that platform. This site links to the official model page with files and instructions.'],['Are subscriptions open?','Not yet. Several exclusive collections are coming. The catalog, prices and terms will be announced before opening.']],
[['¿El belén es realmente gratuito?','¡Sí! Es un regalo de cariño para todos. Descarga las piezas publicadas y sigue las próximas. No requiere suscripción.'],['¿Puedo imprimir el belén para vender?','Sí. Tio Lira autoriza la venta de piezas físicas del belén sin suscripción. No se permite revender ni redistribuir los archivos digitales.'],['¿Necesito una tienda para registrarme?','No. Personas que imprimen en casa y tiendas pueden registrarse gratis. Indica tu ciudad y contacto comercial para recibir pedidos.'],['¿Por qué hay archivos en MakerWorld?','Algunos modelos son exclusivos de esa plataforma. Este sitio enlaza a la página oficial con archivos e instrucciones.'],['¿Ya están abiertas las suscripciones?','Todavía no. Están llegando varias colecciones exclusivas. Anunciaremos catálogo, precios y condiciones antes de abrir.']]],
 calculator:['Calculadora de impressão','Print cost calculator','Calculadora de impresión'],footer:['Feito de fé, afeto e criatividade brasileira.','Made of faith, love and Brazilian creativity.','Hecho de fe, cariño y creatividad brasileña.'],rights:['Criações autorais.','Original creations.','Creaciones originales.'],admin:['Administração','Administration','Administración'],close:['Fechar','Close','Cerrar'],loading:['Carregando...','Loading...','Cargando...'],error:['Não foi possível enviar. Tente novamente.','Could not send. Please try again.','No se pudo enviar. Inténtalo de nuevo.']
};
export const dictionaries=Object.fromEntries(languages.map((lang,i)=>[lang,Object.fromEntries(Object.entries(rows).map(([key,value])=>[key,value[i]]))]));
